### ISSUE TITLE
[Enhancement] Option to prevent the windows reset to the default size when move the window to other workspace

### ISSUE THREAD

**Issue by daltonnyx** [dawsers/hyprscroller#100]
Do we have a feature that allows windows keep the size when switching workspace yet? I found that when I move window to other workspace, It will be reset to the `default_width` setting.

**Comment by dawsers** [comment]
Yes, we do. Read this issue and the solution [#76](https://github.com/dawsers/hyprscroller/issues/76#issuecomment-2491290995)

There is no way to do this with an option, as explained in the issue I linked above. Hyprland removes the windows from the layout and adds them again when you move them from one workspace to another. So to me, the windows are new. I implemented the selection and move selection dispatchers so you can actually move any window you want anywhere while keeping sizes and relative locations.

[Window Copying/Pasting](https://github.com/dawsers/hyprscroller#window-copyingpasting)
