### ISSUE TITLE
Drag/drop onto col

### ISSUE THREAD

**Issue by Acumane** [dawsers/hyprscroller#12]
When dragging and dropping a window (`bindm` to `movewindow`) on top of a column, it should be admitted—ideally inserted—where dropped.

**Comment by dawsers** [comment]
The same problem as with floating windows again. When you drag a window it becomes floating, so it is removed from the layout. As soon as you drop it, the layout receives it as a new window to be inserted, so I don't know where that window is coming from or if it is a totally new window.

**Comment by dawsers** [comment]
When a window is inserted in the layout (or dragged back in from a floating position), it will be located next to the active one. If in column mode, it will be inserted in the column, below the active one. If in row mode, it will be inserted in a new column to the right of the active one.
