### ISSUE TITLE
fail build on hyprland-git 0.40

### ISSUE THREAD

**Issue by obmutescences** [dawsers/hyprscroller#14]
fail build on hyprland-git 0.40

**Comment by obmutescences** [comment]
[v] version returned: Hyprland, built from branch main at commit cddeec47a1fc0e70d8598fd10c29cd0e9489999f dirty (keybinds: make the keybind manager check for session lock (5894)).
Date: Mon May 6 02:28:14 2024
Tag: v0.40.0-11-gcddeec47, commits: 4617

flags: (if any)


[v] parsed commit cddeec47a1fc0e70d8598fd10c29cd0e9489999f at branch main on Mon May 6 02:28:14 2024, commits 4617
✔ adding a new plugin repository from https://github.com/dawsers/hyprscroller
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] y

 → Cloning https://github.com/dawsers/hyprscroller
✔ cloned
✔ found hyprpm manifest
✔ parsed manifest, found 1 plugins:
 → hyprscroller by dawser version
✔ Hyprland headers OK
 → Building hyprscroller
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/local && PKG_CONFIG_PATH="/home/local/.local/share/hyprpm/headersRoot/share/pkgconfig" make release
cmake -B ./Release -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=
-- The CXX compiler identification is GNU 13.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.1")
-- Checking for modules 'hyprland;pixman-1;libdrm'
--   Found hyprland, version 0.39.1
--   Found pixman-1, version 0.43.4
--   Found libdrm, version 2.4.120
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/hyprpm/local/Release
cmake --build ./Release -j
make[1]: Entering directory '/tmp/hyprpm/local/Release'
[ 25%] Building CXX object CMakeFiles/hyprscroller.dir/src/main.cpp.o
[ 50%] Building CXX object CMakeFiles/hyprscroller.dir/src/dispatchers.cpp.o
[ 75%] Building CXX object CMakeFiles/hyprscroller.dir/src/scroller.cpp.o
In file included from /home/local/.local/share/hyprpm/headersRoot/include/hyprland/src/desktop/../includes.hpp:52,
                 from /home/local/.local/share/hyprpm/headersRoot/include/hyprland/src/desktop/../defines.hpp:1,
                 from /home/local/.local/share/hyprpm/headersRoot/include/hyprland/src/desktop/Window.hpp:3,
                 from /tmp/hyprpm/local/src/scroller.cpp:3:
/home/local/.local/share/hyprpm/headersRoot/include/hyprland/wlroots-hyprland/wlr/types/wlr_layer_shell_v1.h:16:10: fatal error: wlr-layer-shell-unstable-v1-protocol.h: No such file or directory
   16 | #include "wlr-layer-shell-unstable-v1-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/hyprscroller.dir/build.make:104: CMakeFiles/hyprscroller.dir/src/scroller.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/local/.local/share/hyprpm/headersRoot/include/hyprland/src/includes.hpp:52,
                 from /home/local/.local/share/hyprpm/headersRoot/include/hyprland/src/defines.hpp:1,
                 from /home/local/.local/share/hyprpm/headersRoot/include/hyprland/src/Compositor.hpp:7,
                 from /tmp/hyprpm/local/src/dispatchers.cpp:1:
/home/local/.local/share/hyprpm/headersRoot/include/hyprland/wlroots-hyprland/wlr/types/wlr_layer_shell_v1.h:16:10: fatal error: wlr-layer-shell-unstable-v1-protocol.h: No such file or directory
   16 | #include "wlr-layer-shell-unstable-v1-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/hyprscroller.dir/build.make:90: CMakeFiles/hyprscroller.dir/src/dispatchers.cpp.o] Error 1
In file included from /home/local/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../debug/../includes.hpp:52,
                 from /home/local/.local/share/hyprpm/headersRoot/include/hyprland/src/config/../debug/Log.hpp:7,
                 from /home/local/.local/share/hyprpm/headersRoot/include/hyprland/src/config/ConfigManager.hpp:6,
                 from /tmp/hyprpm/local/src/main.cpp:1:
/home/local/.local/share/hyprpm/headersRoot/include/hyprland/wlroots-hyprland/wlr/types/wlr_layer_shell_v1.h:16:10: fatal error: wlr-layer-shell-unstable-v1-protocol.h: No such file or directory
   16 | #include "wlr-layer-shell-unstable-v1-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/hyprscroller.dir/build.make:76: CMakeFiles/hyprscroller.dir/src/main.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/hyprscroller.dir/all] Error 2
make[1]: *** [Makefile:91: all] Error 2
make[1]: Leaving directory '/tmp/hyprpm/local/Release'
make: *** [Makefile:13: release] Error 2


✖ Plugin hyprscroller failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first.
  Try re-running with -v to see more verbose output.

**Comment by dawsers** [comment]
I don't support `hyprland-git`. If you are on Arch, please try `hyprland`, currently at version 0.39.1. If you need version 0.40, I am sure Arch will update to it in the next few days. I will add support to it then.

**Comment by obmutescences** [comment]
> I don't support `hyprland-git`. If you are on Arch, please try `hyprland`, currently at version 0.39.1. If you need version 0.40, I am sure Arch will update to it in the next few days. I will add support to it then.

i see
