### ISSUE TITLE
Building/installing via hyprpm fails with hyprland 0.40

### ISSUE THREAD

**Issue by GeertJohan** [dawsers/hyprscroller#19]
I ran updates and apparently the hyprland package is now at 0.40.

```
$ sudo pacman -Q hyprland                                                          ⏎
hyprland 0.40.0-1
```

The hyprscroller plugin fails to start after rebooting.

Running `hyprpm update` fails with:

```
[...]

cp ./protocols/*.h /home/geertjohan/.local/share/hyprpm/headersRoot/include/hyprland/protocols
cp: cannot stat './protocols/*.h': No such file or directory

[...]

/home/geertjohan/.local/share/hyprpm/headersRoot/include/hyprland/wlroots-hyprland/wlr/types/wlr_layer_shell_v1.h:16:10: fatal error: wlr-layer-shell-unstable-v1-protocol.h: No such file or directory
   16 | #include "wlr-layer-shell-unstable-v1-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[...]

✖ Plugin hyprscroller failed to build.
```

Full log: https://gist.github.com/GeertJohan/eeb6fe55c44c3529e4c818431b13ea3d

Related issue #14

**Comment by dawsers** [comment]
If you are on Arch and not using `hyprland-git` but `hyprland`, that's what I am using. You probably need to wipe out the `hyprpm` cache and rebuild.

``` bash
rm -rf ~/.local/share/hyprpm
hyprpm update
hyprpm add https://github.com/dawsers/hyprscroller
hyprpm update
```

The first `update` should bring the correct headers again. The second `update` rebuilds `hyprscroller`.

Then exit and re-log in.

**Comment by GeertJohan** [comment]
Thanks! I just did those steps but hyprpm keeps failing with:
```
$ hyprpm update

 ╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0 / 5  Cloning the hyprland repo! Cloning https://github.com/hyprwm/hyprland, this might take a moment.
 ╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0 / 5  Cloning the hyprland repo✔ cloned
 ╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0 / 5  Cloning the hyprland repo✔ checked out to running ver
! configuring Hyprland
✔ configured Hyprland
✖ failed to install headers with error code 2
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Failed

✖ Headers missing. Please run hyprpm update to fix those.
```

**Comment by dawsers** [comment]
You seem to have a problem installing the hyprland headers, which are needed to re-build any plugins.

This is a hyprland issue. I can only suggest you may not have all the dependencies installed: `cmake`, `meson`, `cpio` and `git`. If you don't, install the packages before trying to update again, and then repeat the process.

Try running `hyprpm --verbose update` to see where the problem happens when installing the headers. It will give you more information.

If that doesn't work, you will need to ask the hyprland guys for help.
