### ISSUE TITLE
Option to center windows by default

### ISSUE THREAD

**Issue by adwaymalhotra** [dawsers/hyprscroller#25]
It would be great if we could set the center alignment as default for all windows. 

I usually prefer the active window to stay in the middle, and move to a different alignment when I actually need to refer to multiple windows. 

AFAIK this is not possible at the moment with the plugin at the moment.

**Comment by dawsers** [comment]
This was explained in #18

**Comment by adwaymalhotra** [comment]
Thanks, that works!
