### ISSUE TITLE
follow_mouse=0 is not respected; hovering with follow_mouse=0|2 moves unfocused window

### ISSUE THREAD

**Issue by adwaymalhotra** [dawsers/hyprscroller#26]
If I have two windows A and B with 2/3 width each. If A is active, then B will be half on screen and half off screen. 

If I hover over B in this scenario, then A becomes half off screen and B is displayed completely. This is not what I expect with `follow_mouse=0` or `follow_mouse=2` in the hyprland input settings.

I would expect that the active window will not move until the focused window changes completely (on click). It gets a bit annoying right now if my cursor accidently moves to the next window. This also changes the alignment of the active window, which at least should not change.  

edit: actually, the focus shifts on hovering an inactive window which is worse than I reported initially.

**Comment by dawsers** [comment]
I use `follow_mouse = 2` in my configuration as in:

```
input {
  follow_mouse = 2
}
```

and focus doesn't change unless I click on a window.

Verify you don't have some other `follow_mouse` in your configuration.

**Comment by adwaymalhotra** [comment]
Well, I don't know what to tell you, this does not seem to be an issue now!
