### ISSUE TITLE
[ Feat ] : multiple scrollers

### ISSUE THREAD

**Issue by Aqa-Ib** [dawsers/hyprscroller#28]
Hey, thanks for this great plugin, I am really enjoying it ! 

I wonder what would be the complexity required for having for example three columns of scrollers, one beside the other, having the ability to be sized independently ?

Do you imagine this being easy or difficult to achieve and maintain ?

**Comment by dawsers** [comment]
Do you mean three rows? You can have three columns right now, and each column can have its own width, and each window its own height. You just need to use row/column mode to create the columns/windows and resize each one as you wish.

**Comment by Aqa-Ib** [comment]
That is really cool, I didn't know, thanks !
Now I see that the structure of the grid is made around columns.
I will try to play with the source code to see if I can put together a structure around rows, maybe even a more rigid one around both rows and columns. Maybe we can have an option to select which structure we want to use.

Cheers.
