### ISSUE TITLE
Bug: floating windows are not handled in focus move

### ISSUE THREAD

**Issue by aacebedo** [dawsers/hyprscroller#3]
When a window is floating, it is impossible to move the focus on it with the dispatcher. This forces to use the mouse to grab the focus again and to retoggle floating state.

**Comment by dawsers** [comment]
In Hyprland, floating windows are not handled by a layout. I think none of the standard layouts (Master, Dwidle) handle floating windows. When a window becomes floating, it is removed from the layout by calling `onWindowRemovedTiling()`, so there is nothing we can do there. You will depend on mouse and the standard Hyprland functions, which I am sure could be improved.

**Comment by aacebedo** [comment]
You are right, I am going to open an issue on this on hyprland.
