### ISSUE TITLE
Nix Flake build problem

### ISSUE THREAD

**Issue by mentalblock** [dawsers/hyprscroller#33]
Hello,
I am trying to get this to build using the Nix flake yet I get the following error.

```
warning: input 'hyprscroller/hyprland/hyprlang' has an override for a non-existent input 'hyprutils'
error: builder for '/nix/store/ccrkvb0z4v13rih75sj58f1dbg9rkh6m-hyprland-0.41.2+date=2024-06-30_d7ea1b7.drv' failed with exit code 1;
       last 10 log lines:
       >   Could not find a configuration file for package "hyprwayland-scanner" that
       >   is compatible with requested version "0.3.10".
       >
       >   The following configuration files were considered but not accepted:
       >
       >     /nix/store/gcayvkjd1i3c91jw6s9c7axm0f6b5yn5-hyprwayland-scanner-0.1.0+date=2024-05-03_1270eba/lib/cmake/hyprwayland-scanner/hyprwayland-scanner-config.cmake, version: 0.3.4
       >
       >
       > 
       > -- Configuring incomplete, errors occurred!
```

I am using the following input declaration in my flake:
```
    hyprscroller = {
      url = "github:dawsers/hyprscroller";
      inputs.hyprland = {
        type = "git";
        url = "https://github.com/hyprwm/Hyprland";
        submodules = true;
      };
    };
```

I am not sure if there is something I am doing incorrectly. Thanks for the investigation.

cc: @howyay

**Comment by howyay** [comment]
My apologies, I've been away recently, I'll get this sorted our within the next couple days.

**Comment by howyay** [comment]
Have you tried `nix flake update` to update the flake inputs yet? If that doesn't do, would you be so kind to provide your `flake.nix` with more context as well as your hyprland configuration for home-manager?

**Comment by mentalblock** [comment]
No rush.

Instead of trying to get hyprscroller to build in my flake, I decided the simpler option would be to attempt to get it to build by checking out this repository and executing a `nix build`. I receive the same error as initially reported.

Therefore, it is shown that it is not likely related to my environment.

**Comment by howyay** [comment]
Thank you, I was able to replicate it with the current repo tree. It's a case of outdated flake inputs and I was able to resolve the error after running `nix flake update`. Though even with that resolved, the `hyprland` input on this flake is missing git `submodules` support, so it will fail to a different error. 

I will make a commit soon-ish to update the `flake.lock` and add `submodules = true`. 

In the meanwhile, if you are using this flake as an input in your own flake, you should be able to resolve it by updating your own `flake.lock` with `nix flake update` and ensuring that `nix flake info` shows that the `hyprwayland-scanner` input under `hyprland` is on a commit no earlier than [0f30f9e](https://github.com/hyprwm/hyprwayland-scanner/commit/0f30f9eca6e404130988554accbb64d1c9ec877d) (0.3.10)

**Comment by mentalblock** [comment]
Thanks for the guidance. In the end I think I will wait until you update this repository. My reasoning is that if I override inputs, especially nested ones, it will be more maintenance effort in the long run.

**Comment by howyay** [comment]
Sorry, I wasn't very clear. Looking at your flake snippet, you are overriding the `hyprland` input to this flake with your own definition, so you'd have to update the locked revision for `hyprland`  with either `nix flake update` (to update everything) or `nix flake lock` (to only update `hyprland`) on your end to fix the compilation error. 

What I was referring to earlier is fixing `nix build` when someone clones this repo, in which case the `hyprland` input refers to the revision locked by the current repo tree.
