### ISSUE TITLE
Question: Set mode per monitor?

### ISSUE THREAD

**Issue by rbutera** [dawsers/hyprscroller#40]
Are we able to set scrolled mode per monitor?

I have a landscape monitor and a portrait secondary monitor and I would love for hyprscroller to be row mode on the former and column mode on the latter.

Is this possible?

**Comment by dawsers** [comment]
The scrolling mode is per workspace (or "scroller"). So if you have two monitors, you can set the dispatch `scroller:setmode row` (default anyway) for workspaces on your horizontal monitor, and `scroller:setmode col` for the ones on your vertical monitor.  That will be like setting a mode per monitor. You can do this manually or with a script called when you login.

**Comment by rbutera** [comment]
I'm really new to hyprland, do you mind explaining to me how I could do this with a script? Sorry

**Comment by dawsers** [comment]
I have implemented an option (9f998f8dfc2bd637d665f3110b67e303894f72bf) called `monitor_modes` where you can specify a default mode per monitor.

For example, if your portrait mode monitor is DP-2, add an option `monitor_modes = DP-2=col` as explained in the README.

**Comment by rbutera** [comment]
> I have implemented an option (9f998f8dfc2bd637d665f3110b67e303894f72bf) called `monitor_modes` where you can specify a default mode per monitor.
> 
> For example, if your portrait mode monitor is DP-2, add an option `monitor_modes = DP-2=col` as explained in the README.

You're amazing. Thank you.
