### ISSUE TITLE
Incompatible with hyprbar

### ISSUE THREAD

**Issue by npc-z** [dawsers/hyprscroller#43]
The part of the hyprbar that doesn't show up on the screen is as if it's beyond the screen. 
When I use overview mode I can see the hyprbar section

**Comment by dawsers** [comment]
I see. It seems I am not reserving space for decorations. I will have a look at it this week. Thanks!

**Comment by npc-z** [comment]
Glad to hear it, thank you so much for your work

**Comment by dawsers** [comment]
This should be fixed in f43a0d4ee839e3a6a3a2fe992b5ee8f78fbe0b11

I don't use decorations, so my testing has been very basic. Let me know how it goes...
