### ISSUE TITLE
windowrules

### ISSUE THREAD

**Issue by cycomanic** [dawsers/hyprscroller#45]
Awesome plugin! I'm so glad I found this. 

I was wondering if it was possible to implement windowrules based on scroller. E.g. one use case I have is that I often need to temporarily open lots of figures from python scripts. If they open up in lots of columns that becomes often annoying, because I still want to easily look at my script or the ipython console, so I would  great to specify a window rule which puts all figures into a single column instead.

**Comment by dawsers** [comment]
I think it's worth exploring. I need to figure out how it would work. Like you mention, it would be a static rule with prefix `scroller:`. Matching rules would need to be queried every time a window is created. When the window gets added to the layout, the rules would be filtered and if one related to `mode` exists, then the window would be added to the workspace following that mode. I just need to see if custom rules actually work and I can get them from the layout plugin, or the Config manager filters any unknown rule out.

I am currently working on fixing a bug, which is requiring some rewrite, but I will definitely have a look at this.

**Comment by dawsers** [comment]
At the moment, Hyprland doesn't allow plugins to create their own window rules.

I filed an issue to discuss that topic https://github.com/hyprwm/Hyprland/issues/7622

I also added some code to `onWindowCreatedTiling` that seems to work if I modify Hyprland. I will enable it if things change on Hyprland's side.

**Comment by dawsers** [comment]
This is added in 3d8503afa712a4d4f4b48a79e6bd48847ecb912b

For your use case, you can create a rule like this:

```
windowrulev2 = plugin:scroller:group python_plots, class:(python3)
```
