### ISSUE TITLE
Fails to compile on NixOS

### ISSUE THREAD

**Issue by robbins** [dawsers/hyprscroller#46]
I've locked my Hyprland input to v0.42.0:
```
    hyprland = {
      type = "git";
      url = "https://github.com/hyprwm/Hyprland?tag=v0.42.0";
      submodules = true;
    };
```
and have set `hyprscroller` to follow this Hyprland version:
```
    hyprscroller = {
      url = "github:dawsers/hyprscroller";
      inputs.hyprland.follows = "hyprland";
    };
```

When rebuilding, I get this compilation error:
```
[ 25%] Building CXX object CMakeFiles/hyprscroller.dir/src/main.cpp.o
In file included from /nix/store/wl7xs26116sswgw18pnc3yw9r5gxr6hx-gcc-13.3.0/include/c++/13.3.0/bits/shared_ptr_base.h:59,
                 from /nix/store/wl7xs26116sswgw18pnc3yw9r5gxr6hx-gcc-13.3.0/include/c++/13.3.0/bits/shared_ptr.h:53,
                 from /nix/store/wl7xs26116sswgw18pnc3yw9r5gxr6hx-gcc-13.3.0/include/c++/13.3.0/chrono:49,
                 from /nix/store/r3j03fs6ia8hpk9wf0kic3h82f5nhv5j-hyprland-0.42.0+date=2024-08-31_cac59fe-dev/include/hyprland/src/debug/Log.hpp:6,
                 from /nix/store/r3j03fs6ia8hpk9wf0kic3h82f5nhv5j-hyprland-0.42.0+date=2024-08-31_cac59fe-dev/include/hyprland/src/config/ConfigManager.hpp:6,
                 from /build/source/src/main.cpp:1:
/nix/store/wl7xs26116sswgw18pnc3yw9r5gxr6hx-gcc-13.3.0/include/c++/13.3.0/bits/unique_ptr.h: In instantiation of 'constexpr std::__detail::__unique_ptr_t<_Tp> std::make_unique(_Args&& ...) [with _Tp = ScrollerLay>
/build/source/src/main.cpp:48:1:   required from here
/nix/store/wl7xs26116sswgw18pnc3yw9r5gxr6hx-gcc-13.3.0/include/c++/13.3.0/bits/unique_ptr.h:1070:30: error: invalid new-expression of abstract class type 'ScrollerLayout'
 1070 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /build/source/src/main.cpp:6:
/build/source/src/scroller.h:11:7: note:   because the following virtual functions are pure within 'ScrollerLayout':
   11 | class ScrollerLayout : public IHyprLayout {
      |       ^~~~~~~~~~~~~~
In file included from /build/source/src/scroller.h:1:
/nix/store/r3j03fs6ia8hpk9wf0kic3h82f5nhv5j-hyprland-0.42.0+date=2024-08-31_cac59fe-dev/include/hyprland/src/layout/IHyprLayout.hpp:66:18: note:     'virtual void IHyprLayout::recalculateMonitor(const MONITORID&)'
   66 |     virtual void recalculateMonitor(const MONITORID&) = 0;
      |                  ^~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/hyprscroller.dir/build.make:76: CMakeFiles/hyprscroller.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/hyprscroller.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

This is the only error I get, and it seems it existed when hyprscroller wasn't updated to the Hyprland 0.42.0 API, but seems to have been fixed: https://github.com/dawsers/hyprscroller/issues/39

I see the error here on the Git version: https://github.com/dawsers/hyprscroller/issues/42 but I should be on the tagged release. @howyay Since you were the one who added the flake, am I using it correctly in my config?

**Comment by cpiber** [comment]
The `recalculateMonitor` was changed in https://github.com/hyprwm/Hyprland/commit/4b4971c06fb02df00a2bd20b6b47b5d0e7d799a7, which is *right after* 0.42.0, so something in there does not properly pin hyprland, not familar with Nix though

**Comment by dawsers** [comment]
I don't know how NixOS configuration works, but you are compiling `hyprscroller` against Hyprland headers that are not for version 0.42.0. The error you see about `virtual void recalculateMonitor(const MONITORID&) = 0;` happens because your headers are newer than v0.42.0, where this function takes an integer instead of MONITORID.

Are you compiling manually or using `hyprpm`?

**Comment by robbins** [comment]
> The `recalculateMonitor` was changed in [hyprwm/Hyprland@4b4971c](https://github.com/hyprwm/Hyprland/commit/4b4971c06fb02df00a2bd20b6b47b5d0e7d799a7), which is _right after_ 0.42.0, so something in there does not properly pin hyprland, not familar with Nix though

I think you're right, I see that it's somehow on HEAD~1 of Hyprland:
```
nix-repl> inputs.hyprland.rev
"cac59fefecaefe34be45e65713d54676444f88a2"
```

so it's not being pinned correctly.



> I don't know how NixOS configuration works, but you are compiling `hyprscroller` against Hyprland headers that are not for version 0.42.0. The error you see about `virtual void recalculateMonitor(const MONITORID&) = 0;` happens because your headers are newer than v0.42.0, where this function takes an integer instead of MONITORID.
> 
> Are you compiling manually or using `hyprpm`?

Yeah, that makes sense with the above.

After some Googling I was able to correctly specify the version in Nix and it compiles correctly now - sorry for the false alarm issue.

Sidenote, do you have your dotfiles public somewhere? I really like your Hyprland & Bar setup in the README GIF.

**Comment by dawsers** [comment]
I haven't made my configuration files public, but I have no problem sharing. For the bar I use [ags](https://github.com/Aylur/ags) with several modules I wrote in Javascript (calendar, weather, music player, CPU/MEM/GPU graphs,...). It's all very sadly colored (mostly black backgrounds), but I prefer functional over flashy. The rest is Neovim with a theme I wrote and configured using "literate programming" (the configuration file is a Markdown document that gets converted at runtime into the `init.lua`).

If you're interested in anything in particular, let me know and I may create a small repository with the files.

**Comment by howyay** [comment]
> After some Googling I was able to correctly specify the version in Nix and it compiles correctly now with ` hyprland.url = "git+https://github.com/hyprwm/Hyprland?submodules=1&rev=9a09eac79b85c846e3a865a9078a3f8ff65a9259";` - sorry for the false alarm issue.

I believe the way in which you pinned the flake input is incorrect - to pin by version (in the form of tags) for a flake input of type `git`, you should instead have the following: 

```nix
inputs.hyprland = {
      type = "git";
      url = "https://github.com/hyprwm/Hyprland";
      submodules = true;
      ref = "refs/tags/v0.42.0";
}
```

There might be other valid syntax for specifying tag refs for `git` type inputs that I'm not aware of, but I believe the one you were initially using is not one of them. @robbins 

Sorry for the late response!

**Comment by pipelight** [comment]
Thx @howyay version pinning was the thing that made it all right!
