### ISSUE TITLE
Idea, Behavior similar to a newm

### ISSUE THREAD

**Issue by CRAG666** [dawsers/hyprscroller#5]
WorkCase:

https://www.youtube.com/watch?v=mDw-hMW0b70

Thanks

**Comment by dawsers** [comment]
The feature I find interesting at first is being able to change focus when in full screen mode. That is something I am planning to implement. The rest is very pretty, but I see some issues, like all the windows are the same size for this to work transparently, and the need to use the mouse in some workflows.

Please, explain what features you miss (aside from full screen focus change) so I can think if/how they would work for this project.

Thanks!

**Comment by CRAG666** [comment]
I really miss being able to have windows up and down instead of just having them on one side.
My normal flow with newm is to move both up and down, left and right, and also move diagonally. Believe me, I even abandoned the use of a second monitor for the ease of moving around on just one.
By the way, it doesn't depend on the mouse, everything can be controlled by keyboard, however the touchpad gestures are wonderful.
In general what I miss the most is the mosaic design. Having my own work layout makes my flow multiply.
By the way, thank you very much for this wonderful project, I was waiting for something for months, I would like to contribute to the project, but unfortunately I am studying a master's degree that absorbs all my time.
@dawsers Thanks

**Comment by CRAG666** [comment]
I almost forgot, a feature that I would like to have is the ability to select in which position the new windows will be, for example currently if I apply the analogy that I want to propose, the windows will be down in proportion of 1, therefore the opening is infinite to the right.

Diagram: Imagine setting the aperture down:3, Opening the windows would behave as follows:

First window:
![imagen](https://github.com/dawsers/hyprscroller/assets/34254373/93a41736-d426-492e-9620-155e8f79ac68)

Second Window:
![imagen](https://github.com/dawsers/hyprscroller/assets/34254373/400274d8-1598-42e2-bbfe-4225768d9f93)
Third Window:
![imagen](https://github.com/dawsers/hyprscroller/assets/34254373/01089478-9bea-42cf-a90a-0d90ba15da53)
when the limit established in this case 3 is reached, then it restarts but in this case the new window opens on the left:
![imagen](https://github.com/dawsers/hyprscroller/assets/34254373/54732e67-e216-44ee-bf8a-b8a50de0f7bf)
![imagen](https://github.com/dawsers/hyprscroller/assets/34254373/a32792c6-e930-407b-b3f3-1be0152b24e8)
![imagen](https://github.com/dawsers/hyprscroller/assets/34254373/2937c230-a008-40bb-83fd-a376bfe3cb38)
![imagen](https://github.com/dawsers/hyprscroller/assets/34254373/cf6038a6-c87b-4c14-85ae-464d52f788eb)
with a down:3 configuration we limit the growth by three, but the growth to the right is still infinite
but if for example we configure right:3 we limit the growth to the right to 3 windows but down it is infinite

**Comment by CRAG666** [comment]
What I wrote allows movement either up, down, left, right and the 4 diagonals

**Comment by CRAG666** [comment]
My idea was only about making the movements faster, instead of pressing so many keys to go to a window, moving in a grid is fast, since you can go up, down, left, right, etc.

**Comment by dawsers** [comment]
You can also call `toggleoverview` and move like if you had a grid. If you change the key bindings like the README file, you can focus windows using the arrow keys. 

*overview* mode is similar to what you could do in *newm* when zooming out. All the features are available while you are "zoomed out".

But if there are other things you miss and would fit here, of course I would be very thankful to hear them.

**Comment by dawsers** [comment]
I have made changes to columns which are now more useful. The overview mode is also improved. I am not going to build newm into this plugin, but I think the current functionality should allow quite similar workflows.

**Comment by CRAG666** [comment]
@dawsers this is amazing, thans, I would just like to be able to add a limit in the column and row mode to move on to the next one so that I have more sensible behavior when opening windows and remembering which ones I have inhabited.
