### ISSUE TITLE
feature: ability to configure defaults per mode

### ISSUE THREAD

**Issue by samflores** [dawsers/hyprscroller#54]
I have a 2 monitors setup and hyprscroller works quite beautifully with it, but I want to use my secondary screen in vertical orientation. 

I know I can use `monitor_modes` to set it to column mode but then as `default_column_width` is shared width my wide horizontal monitor it makes new clients too narrow.

Ideally, it would be great to be able to set a different value for `default_column_width` and `default_window_height` based on the mode (`col` or `row`).

**Comment by dawsers** [comment]
I added this in 3cdf011b1641987448120f5c7f21acc9d7ed610c

It works as a new option: `monitor_options` where you can define per monitor variables. It is explained in the README, under `Options`, in `monitor_options`.

I hope it works for you.

**Comment by samflores** [comment]
Thank you! It works perfectly.
