### ISSUE TITLE
How to know whether I am in row/column mode

### ISSUE THREAD

**Issue by Chen-Yulin** [dawsers/hyprscroller#57]
Hi, I really appreciate this awesome plugin!!
I was wondering how can I get the current mode of hyprscroller, so that I can display the mode in waybar or somewhere else.
Also, it's quite helpful if I can see whether I am in overview (since for workspace with only two windows, the overview looks the same as normal view).

THANKS!!!

**Comment by dawsers** [comment]
Thank you, I am glad you find it useful.

I added two IPC messages to do what you want in af6bd79229d0b6676af7f95c8dccd986a77b3c7c

There is some documentation in the README to explain how to use them, subsection IPC. For a quick example, you can use this script:

``` sh
#!/usr/bin/env bash

function handle {
  if [[ ${1:0:8} == "scroller" ]]; then
    if [[ ${1:10:11} == "overview, 0" ]]; then
        hyprctl notify -1 3000 "rgb(ff1ea3)" "Normal mode!"
    elif [[ ${1:10:11} == "overview, 1" ]]; then
        hyprctl notify -1 3000 "rgb(ff1ea3)" "Overview mode!"
    elif [[ ${1:10:9} == "mode, row" ]]; then
        hyprctl notify -1 3000 "rgb(ff1ea3)" "Row mode!"
    elif [[ ${1:10:12} == "mode, column" ]]; then
        hyprctl notify -1 3000 "rgb(ff1ea3)" "Column mode!"
    elif [[ ${1:10:11} == "admitwindow" ]]; then
        hyprctl notify -1 3000 "rgb(ff1ea3)" "Admit Window!"
    elif [[ ${1:10:11} == "expelwindow" ]]; then
        hyprctl notify -1 3000 "rgb(ff1ea3)" "Expel Window!"
    fi
  fi
}

socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
```

You can adapt it to the way your bar works.

For the particular case of `overview`, the way I know I am in that mode is because I use a special submap for it. That way I can disable certain "dangerous" keys while I am in `overview`. I use [ags](https://github.com/Aylur/ags), which provides a `submap` module for *hyprland*.

```
# overview keys
# bind key to toggle overview (normal)
bind = $mainMod, tab, scroller:toggleoverview
# bind mouse button to toggle overview
bind = ,mouse:275, scroller:toggleoverview
# overview submap
# will switch to a submap called overview
bind = $mainMod, tab, submap, overview
# will start a submap called "overview"
submap = overview
bind = , right, scroller:movefocus, right
bind = , left, scroller:movefocus, left
bind = , up, scroller:movefocus, up
bind = , down, scroller:movefocus, down
bind = CTRL, left, scroller:movewindow, l
bind = CTRL, right, scroller:movewindow, r
bind = CTRL, up, scroller:movewindow, u
bind = CTRL, down, scroller:movewindow, d
bind = CTRL, home, scroller:movewindow, begin
bind = CTRL, end, scroller:movewindow, end
# use reset to go back to the global submap
bind = , escape, scroller:toggleoverview,
bind = , escape, submap, reset
bind = , return, scroller:toggleoverview,
bind = , return, submap, reset
bind = $mainMod, tab, scroller:toggleoverview,
bind = $mainMod, tab, submap, reset
# will reset the submap, meaning end the current one and return to the global one
submap = reset
```

Let me know if you need anything else.

**Comment by Chen-Yulin** [comment]
![image](https://github.com/user-attachments/assets/4ae55b51-2ea0-4ac6-87fc-dc021d480ca5)
Works well on my machine.
Thank you very much!

**Comment by Chen-Yulin** [comment]
![Pasted image 20241017092056](https://github.com/user-attachments/assets/670ff858-e3df-479b-934c-33bcdc6bfd05)
![Pasted image 20241017092323](https://github.com/user-attachments/assets/76274ce5-349d-4ec9-b244-8ccebf8340e0)


Here is how I use the IPC msg to complete the scroll mode module in waybar!

I wrote two shell script under `~/.config/waybar/`
- `scroller_mode_listener.sh`, responsible for listening the IPC message of `hyprscroller` and store that information in a tmp file. This script can be executed in hyprland config file using `exec-once`.
```bash
#!/bin/bash

MODE_FILE="/tmp/hyprland_scroller_mode"

function handle {
  if [[ ${1:0:8} == "scroller" ]]; then
    if [[ ${1:10:9} == "mode, row" ]]; then
        echo "Row" > "$MODE_FILE"
    elif [[ ${1:10:12} == "mode, column" ]]; then
        echo "Column" > "$MODE_FILE"
    #else
        #echo "" > "$MODE_FILE"
    fi
    hyprctl dispatch submap reset && pkill -SIGRTMIN+8 waybar # update the widget on waybar
  fi
}

# Initialize the mode file
echo "" > "$MODE_FILE"

socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
```
- `scroller_mode_reader.sh`, responsible for reading the tmp file and return the `json` value to waybar to change the shown icon.
```bash
#!/bin/bash

MODE_FILE="/tmp/hyprland_scroller_mode"

current_mode=$(cat "$MODE_FILE")

if [[ "$current_mode" == "Row" ]]; then
    icon="Row"
    percent=0
    class="mode-row"
elif [[ "$current_mode" == "Column" ]]; then
    icon="Column"
    percent=100
    class="mode-column"
else
    icon="Row"
    percent=0
    class=""
fi

echo "{\"text\":\"$icon\", \"tooltip\":\"Scroller Mode: $current_mode\", \"class\":\"$class\",\"percentage\": $percent}"
```

Then add the custom module to waybar in config file (we use signal to update the module):
```json
    "custom/scroller-mode": {
        "exec": "~/.config/waybar/scroller_mode_reader.sh",
        "return-type": "json",
        "interval": "once",
        "signal": 8,
        "on-click": "hyprctl dispatch submap reset && pkill -SIGRTMIN+8 waybar",
        "format": "{icon}",
        "format-icons": ["", ""],
    }
```

Also remember to add the module to the bar:
```json
    "modules-right": ["custom/scroller-mode", "cpu", "memory", "temperature","battery","clock","custom/power"],
```

Then everything is done.

**Comment by dawsers** [comment]
Very cool! I'll make a link to your comment from the README. Thank you!

**Comment by dovbaeb** [comment]
Cannot get it to work at launch, I have to manually start the listener, despite waybar/ being in my path.. I've tried multiple things to no avail...

**Comment by dawsers** [comment]
I cannot help much because I use ags, but try to use the full path of the script in your configuration and see if that works. Depending on how you start Hyprland, your PATH may not be set yet. So try something like:

```
exec-once = /home/dovbaeb/.config/waybar/scripts/scroller_mode_reader.sh
```

**Comment by dovbaeb** [comment]
you need to run reader o listener at launch ? do they have to be in /scripts folder ? I've just put em in /waybar and only start listener on startup maybe thats my issue ?

**Comment by dovbaeb** [comment]
welp running both at launch using your method doesn't work either :/

**Comment by dovbaeb** [comment]
oh no wow now it works thank you idk what i changed but it's all good, thanks !

**Comment by shackra** [comment]
I'm unable to make the listener work unless I run it on a shell. Portion of my configuration which I manage with home-manager:

```
 88   │ exec-once=systemctl --user start hyprpolkitagent
  89   │ exec-once=dex --autostart --search-paths "$HOME/.config/autostart"
  90   │ exec-once=hyprwall -r
  91   │ exec-once=swaync
  92   │ exec-once=sleep 1 && waybar
  93   │ exec-once=/nix/store/4x3wr09qr80rdsanwy5y9rrw5bxfg854-scroller_mode_listener
```

the script in question:

```
➜  bat /nix/store/4x3wr09qr80rdsanwy5y9rrw5bxfg854-scroller_mode_listener
───────┬───────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /nix/store/4x3wr09qr80rdsanwy5y9rrw5bxfg854-scroller_mode_listener
───────┼───────────────────────────────────────────────────────────────────────────────────────────────
   1   │ #!/nix/store/p6k7xp1lsfmbdd731mlglrdj2d66mr82-bash-5.2p37/bin/bash
   2   │ MODE_FILE="/tmp/hyprland_scroller_mode"
   3   │
   4   │ function handle {
   5   │   if [[ ${1:0:8} == "scroller" ]]; then
   6   │     if [[ ${1:10:9} == "mode, row" ]]; then
   7   │         echo "Row" > "$MODE_FILE"
   8   │     elif [[ ${1:10:12} == "mode, column" ]]; then
   9   │         echo "Column" > "$MODE_FILE"
  10   │     #else
  11   │         #echo "" > "$MODE_FILE"
  12   │     fi
  13   │     hyprctl dispatch submap reset && pkill -SIGRTMIN+8 waybar # update the widget on waybar
  14   │   fi
  15   │ }
  16   │
  17   │ # Initialize the mode file
  18   │ echo "" > "$MODE_FILE"
  19   │
  20   │ socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | whil
       │ e read -r line; do handle "$line"; done
───────┴───────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by dawsers** [comment]
It may be related to the previous post, some environment variables are not set when Hyprland is launched. If you start Hyprland from a session manager or `.bash_profile`, your whole environment is not set yet. Instead, when you run your script from the shell, anything you set in `.bashrc` is available (modifications to your path or other environment variables you may have set there).

So I can only suggest you try to get a log or run Hyprland from the tty to see what the error looks like. Depending on how you start Hyprland, you may need to set more environment variables for the script to work.

I am sorry I cannot be of much more help. I don't use NixOS or waybar.

**Comment by Chen-Yulin** [comment]
> I'm unable to make the listener work unless I run it on a shell. Portion of my configuration which I manage with home-manager:
> 
> ```
>   88   │ exec-once=systemctl --user start hyprpolkitagent
>   89   │ exec-once=dex --autostart --search-paths "$HOME/.config/autostart"
>   90   │ exec-once=hyprwall -r
>   91   │ exec-once=swaync
>   92   │ exec-once=sleep 1 && waybar
>   93   │ exec-once=/nix/store/4x3wr09qr80rdsanwy5y9rrw5bxfg854-scroller_mode_listener
> ```

try to use a terminal emulator to launch the script like `exec-once=alacritty -e /nix/store/4x3wr09qr80rdsanwy5y9rrw5bxfg854-scroller_mode_listener`, idk why, but it's the recent feature of hyprland i think.

**Comment by tombombadilaudid** [comment]
I had used Chen's Waybar integration scripts in the past but had switched away from Hyprscroller for a while and when I switched back I couldn't get the listener to autostart with exec-once or by including it in other startup scripts. It worked fine if I manually started it and no amount of debugging I did gave me a reasonable explanation as to why the listener would kill itself if autostarted so I went ahead and wrote another variation that, for me, works with exec-once and combines the functions of both into one script. Not sure if something changed with Hyprland or Waybar or what but if you're having trouble with the one Chen provided give this method a try.


hswbstartup.sh (run with exec-once):
```
#!/bin/bash

MODE_FILE="/tmp/hyprscroller-mode"

handle_mode_listener() {
    case $1 in
        *"scroller>>mode, row"*)
            current_mode="row"
            handle_mode_reader
            hyprctl dispatch submap reset && pkill -SIGRTMIN+8 waybar # && echo "Signal sent."
            ;;
        *"scroller>>mode, column"*)
            current_mode="column"
            handle_mode_reader
            hyprctl dispatch submap reset && pkill -SIGRTMIN+8 waybar # && echo "Signal sent."
            ;;
    esac
}

handle_mode_reader() {
    if [[ "$current_mode" == "row" ]]; then
        icon="Row"
        percent=0
        class="mode-row"
    elif [[ "$current_mode" == "column" ]]; then
        icon="Column"
        percent=100
        class="mode-column"
    else
        icon="Row"
        percent=0
        class=""
    fi

    echo "{\"text\":\"$icon\", \"tooltip\":\"Scroller Mode: $current_mode\", \"class\":\"$class\", \"percentage\": $percent}" > "$MODE_FILE" # && echo "Wrote mode $current_mode to file."
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle_mode_listener "$line"; done
```

Waybar module snippet:
```
    // Hyprscroller Mode Status
    "custom/hyprscroller": {
        "exec": "cat /tmp/hyprscroller-mode",
        "return-type": "json",
        "interval": "once",
        "signal": 8,
        "on-click": "bash $HOME/.config/hypr/plugins/scrollertoggle.sh",
        "format": "{icon}",
        "format-icons": ["ROW \udb80\udde5  ", "COLUMN \udb81\udf02 "],
    },
```

The Waybar module is set up to run the following scroller mode toggle script (derived from #114 ) when you click the module so you'll need to change or remove that line if you don't intend to use the toggle script. I have the script keybound in addition to the Waybar on-click functionality. I use SwayNC for my notifications so you will need to either remove/modify the notification lines or create/rename the directory and provide your own images depending on your notification setup.

scrollertoggle.sh:
```
#!/bin/bash

HSWB_DIR="$HOME/.config/waybar/hyprscroller-waybar"
MODE_FILE="/tmp/hyprscroller-mode"

current_mode=$(cat "$MODE_FILE")

if [[ "$current_mode" =~ "Row" ]]; then
    hyprctl dispatch -- scroller:setmode column
    notify-send -a "t1" -r 91190 -t 2200 -i "${HSWB_DIR}/column.png" "Column mode active."
elif [[ "$current_mode" =~ "Column" ]]; then
	hyprctl dispatch -- scroller:setmode row
	notify-send -a "t1" -r 91190 -t 2200 -i "${HSWB_DIR}/row.png" "Row mode active."
else
    notify-send -a "t1" -r 91190 -t 2200 -i "${HSWB_DIR}/error.png" "Error: Could not detect current mode."
fi
```

The Waybar module will not show on your bar upon your initial startup/login but will appear once you've opened a window on the currently focused monitor and will remain after closing all windows displaying the last mode you were in. If you open a single window, switch to column mode, then close the lone window on that display or workspace it will still display column until you open another window on that display or workspace at which point it will switch back to row as that is what Hyprscroller defaults to when spawning the first window on a monitor.
