### ISSUE TITLE
Window overflow to adjacent monitor when movefocus

### ISSUE THREAD

**Issue by Yucklys** [dawsers/hyprscroller#58]
I have a three-monitors setup, and the window will overflow to the adjacent monitor when I `movefocus`.
To reproduce, **I set my column width to one half, and opens three window in a row, so it will take 1.5 of my screen width**. So whenever I switch focus between these three windows, the one that is leaving my screen will show on the adjacent screen for a second and then disappear. Below is the recording of my secondary monitor, the window in the main monitor moved to this monitor when I was doing `movefocus`.

https://github.com/user-attachments/assets/8ae6d2dd-25af-4370-a288-52e4123eb078

Another thing might be related, the window remains when I switch to a new workspace. In the recording below, I switched to workspace 2, but the rightmost workspace is still there during the animation.

https://github.com/user-attachments/assets/42e4cf2f-bb34-4f2c-b355-9e23a1bf5a55

 Is there anyway to only display windows in their current workspace?

**Comment by dawsers** [comment]
Yes,, windows "stay there" for a short period in the adjacent monitor. This is a known issue that started after Hyprland v0.35, as explained [here](https://github.com/dawsers/hyprscroller/issues/6#issuecomment-2094119985).

There is basically nothing I can do. Let me know if that is exactly what you mean, or there is something else I am not understanding. Otherwise I will have to close the issue, as there is nothing I can do in the plugin to change that behavior.

**Comment by Yucklys** [comment]
> Yes,, windows "stay there" for a short period in the adjacent monitor. This is a known issue that started after Hyprland v0.35, as explained [here](https://github.com/dawsers/hyprscroller/issues/6#issuecomment-2094119985).
> 
> There is basically nothing I can do. Let me know if that is exactly what you mean, or there is something else I am not understanding. Otherwise I will have to close the issue, as there is nothing I can do in the plugin to change that behavior.

Thanks for your reply. Sorry for making a redundant issue. I really enjoy this plugin, too bad it cannot work perfectly with my setup. I will close this issue due to repeated topic.

**Comment by dawsers** [comment]
Yes, I share your feelings, I also have a multi-monitor setup and see the issue. After almost six months, I am used to it, but it used to be a bit frustrating.

**Comment by dawsers** [comment]
For reference https://github.com/hyprwm/Hyprland/issues/8349
