### ISSUE TITLE
Movefocus r not working in fullscreen

### ISSUE THREAD

**Issue by obmutescences** [dawsers/hyprscroller#61]
after update lastest commit.

bind = $mainMod, W, exec, hyprctl dispatch fullscreen 1 # toggle the window on focus to fullscreen

bind = ALT, Tab, movefocus, r

Then use alt, tab its not working. it is working before.

**Comment by dawsers** [comment]
Hehehe, you are lucky that even worked! Before yesterday, `movefocus` wasn't supported, and you needed to use `scroller:movefocus`. But it seems using `movefocus` in that particular case had a welcome side effect.

I am going to try to make this work properly. Thank you for pointing this out, it will help a lot.

**Comment by dawsers** [comment]
After b512d03964b88bffb47094794e49770190fb32b0, things should work much more consistently. You can create windows, change focus, move windows and use overview while in any of the `fullscreen` modes.

You can even work in full screen all the time, and use overview as a mini-map.

Please, close this issue if you don't find any problems.

**Comment by obmutescences** [comment]
> After [b512d03](https://github.com/dawsers/hyprscroller/commit/b512d03964b88bffb47094794e49770190fb32b0), things should work much more consistently. You can create windows, change focus, move windows and use overview while in any of the `fullscreen` modes.
> 
> You can even work in full screen all the time, and use overview as a mini-map.
> 
> Please, close this issue if you don't find any problems.

Its working. thanks for you working.
