### ISSUE TITLE
Multi-monitor: Animations appear on adjacent monitor

### ISSUE THREAD

**Issue by BinaryInk** [dawsers/hyprscroller#65]
# Issue

When triggering a window animation, the window will appear on the adjacent monitor for the duration of the animation. This occurs whether the window is being brought into focus or is going 'off screen'. Once the animation is completed, the window on the adjacent monitor is no longer visible.

# Relevant Setup Info
`hyprctl monitors`:
```
Monitor DP-1 (ID 0):
	3840x2160@59.99700 at 0x0
	active workspace: 1 (1)
	special workspace: -95 (special:Quake)
	reserved: 0 24 0 23
	scale: 1.50
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
Monitor DP-3 (ID 1):
	2560x1440@59.95100 at 2560x0
	active workspace: 10 (10)
	special workspace: 0 ()
	reserved: 0 24 0 23
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
```
# Misc

The only thing I haven't tested is whether scale affects this or not since my setup involves two different scales. I'm not presently at my desktop; I can test later if needed, though I suspect the issue will persist even if both are at 1.0 scale.

-----

If I get the chance, I can look into the issue further and attempt to offer a fix. C++ is not my forte, however.

**Comment by cpiber** [comment]
Seems a duplicate of #58

**Comment by BinaryInk** [comment]
...yep, it is. Closing. 

I failed to do my due diligence here; just woke up this morning and wanted to get the things I noticed over the past two days posted and admittedly tunnel-visioned on doing *just* that. 

I'll double-check my other issues I opened up a bit ago.

**Comment by dawsers** [comment]
For reference https://github.com/hyprwm/Hyprland/issues/8349
