### ISSUE TITLE
Multi-monitor: Window(s) in a special workspace will only appear on the monitor in which it was spawned

### ISSUE THREAD

**Issue by BinaryInk** [dawsers/hyprscroller#66]
# Issue

If you open up a special workspace on Monitor 1, open a window in the special workspace, then attempt to open the special workspace on Monitor 2, the special workspace will appear to be empty (though waybar & hyprctl reports that the window is open on the special workspace). Opening the special workspace again on Monitor 1 shows the open window(s) as expected.

- This occurs regardless of the monitor the window is first opened on. If it's opened on Monitor 2, it won't show on Monitor 1
- Also occurs if moving the special workspace to the other monitor while the special workspace is open on the inactive monitor.
- Despite not being visible, issuing the `killactive` dispatcher closes the window on the special workspace, indicating the window does have focus.
- Occurs even when switching to Dwindle/Master layout and back to Scroller.
- Interestingly, I believe I have run into a case where it started behaving as expected. I don't know what triggered that, but everything described as above happens when started from boot. If I figure out what happened for it to start behaving as expected (or find out I was mistaken or something along those lines), I'll add to this issue.

# Relevant Setup Info
`hyprctl monitors`:
```
Monitor DP-1 (ID 0):
	3840x2160@59.99700 at 0x0
	active workspace: 1 (1)
	special workspace: -95 (special:Quake)
	reserved: 0 24 0 23
	scale: 1.50
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
Monitor DP-3 (ID 1):
	2560x1440@59.95100 at 2560x0
	active workspace: 10 (10)
	special workspace: 0 ()
	reserved: 0 24 0 23
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
```

# Misc

I haven't tested is whether scale affects this or not since my setup involves two different scales. I'm not presently at my desktop; I can test later if needed, though I suspect the issue will persist even if both are at 1.0 scale.

-----

If I get the chance, I can look into the issue further and attempt to offer a fix. C++ is not my forte, however.

(I think this is the last issue I have noticed...thanks again for the plugin and the work you've put into it.)

**Comment by dawsers** [comment]
Thank you for taking the time to find these bugs and submitting a report. It is hard for me to do proper QA after every Hyprland change, so user feedback is very much appreciated.

This issue (as well as the other related one) should be fixed in c151896a772a74249257ade8dc49f36d7dae813e
