### ISSUE TITLE
Special Workspace minimizes when a pinned floating window is closed on the Special Workspace

### ISSUE THREAD

**Issue by BinaryInk** [dawsers/hyprscroller#68]
# Problem

As the title states, a *pinned* floating window will cause the special workspace to minimize and focus on the last focused window in the workspace behind it. Doesn't happen with windows that open in their own layer, like rofi for instance, and doesn't happen with regular floating windows on the special workspace. It doesn't matter whether the pinned window is opened on the special workspace or not.

I'm assuming this is in some form related to #64 and can be fixed in a similar manner. 

(As for offering a fix...I've cloned the repository but haven't put as much time into understanding it as I'd like to yet. I may look at this in the next week if a fix hasn't already been implemented.)

**Comment by dawsers** [comment]
Let me see if I understand what you mean.

1. I have a regular workspace with three windows open (for example).
2. I make one of them a floating window.
3. I pin that floating window using Hyprland's `pin` (`hyprctl dispatcher pin`), so if I change workspaces in that monitor, it will always show.
4. I open the special workspace and create one window.

Now I can see the special workspace with its window, behind it there will be the floating window and the windows belonging to the regular workspace. That is what I expect.

Now I change to a new (empty) workspace. I can still see the special workspace window and the pinned window. I can turn on or off the special workspace.

I don't see any minimization, so I think I don't understand what you mean, or I haven't followed your instructions correctly.

**Comment by dawsers** [comment]
I get it now, it took me a while. I don't use most of Hyprland's dispatchers (like `pin`) or floating windows, so thank you for taking the time to file the issue.

Don't worry about it, it should be something simple. I will have a look at it.

**Comment by BinaryInk** [comment]
It looks as if this was more of a unique case than I realized.

It works as expected if you spawn a window normally, float it, pin it, then go to the special workspace and close it. Apologies for not thoroughly confirming where the problem is actually arising.

The edge case appears to _actually_ be when the window is spawned with window rules to make it floating and pinned. For example, I have a couple of different TUI tools and scripts bound to keyboard shortcuts to pop up kitty as floating & pinned like so:

```ini
$networkManager = kitty --class nmtui -e 'nmtui'
$networkManagerClass = nmtui
# ...
# Tag all TUI tools: they should all spawn in the same place at the same size.
windowrulev2 = tag +tuiTool, class:($taskwarriorTui|$clipboardHistoryClass|$networkManagerClass|$bluetoothManagerClass|$audioPickerClass|$renameWorkspaceClass|systemctl-failed-tui)
# ...
windowrulev2 = float, tag:tuiTool
windowrulev2 = pin, tag:tuiTool
windowrulev2 = center, tag:tuiTool
windowrulev2 = noblur off, tag:tuiTool
windowrulev2 = size 50% 50%, tag:tuiTool
# ...
# Network manager
bind = $MOD ALT, K, exec, pkill $networkManagerClass || $networkManager
```

So, anything I spawn that's a 'tuiTool' has this problem; I can confirm that I do not have a problem with windows spawned _without_ that ruleset. I can also confirm it's applicable to the latest commit of this plugin; just double-checked after running `hyprpm update`.

**Comment by dawsers** [comment]
Try the latest commit 148a1fd0f48789760b358e9786b953520ff1e128. In my simple testing, it seems to be fixed.

You will need Hyprland v0.45.0, though.
