### ISSUE TITLE
Appears to be some kind of minimium gap size

### ISSUE THREAD

**Issue by notverymoe** [dawsers/hyprscroller#72]
Hi there,

Thanks for the work you do on this project, it's my favorite layout system by far.

I've noticed recently that there appears to be some kind of minimium gap_in/out value preventing borders from touching, additionally changing the gaps value also appears to require some kind of command like `move_focus` to cause a re-layout - thought that's probably not too much of a concern. I've attached an video demonstrating the issue

https://github.com/user-attachments/assets/4c1f7bb7-13b6-4299-be2b-3031085be52e

Running on Arch Linux, been like this the last few times I've updated so I'm not entirely sure when it started occurring. I can provide my config if needed. Apologies if this is unrelated to the layout plugin and is just something I've misconfigured 

Thanks for your time

**Comment by dawsers** [comment]
Thank you, I am glad you are enjoying the plugin.

You are right. I hadn't noticed gaps cannot be zero. It seems Hyprland's concept of reserved space changed and is different than what I am still using. I will have a look at it.

As for the recalculation of windows when `gaps_in` changes, I have committed a change that fixes it 220b10b0ac5682bff1a4cbb67b860eec91132843

**Comment by dawsers** [comment]
I think the `gaps_in` difference is fixed in 07f77ba11942031f1f03b7989c5ebf94636be295.

Please, test it and if it works, we can close this issue.

Thank you for taking the time to fill the report. It is hard for me to keep up with all of Hyprland's changes, because I only use *hyprscroller*, and never any of the standard layouts which are more up-to-date with upstream changes.

**Comment by notverymoe** [comment]
Hi there, 

Sorry I didn't see your reply before now, I just gave it a go and it appears to have worked. Thankyou again!
