### ISSUE TITLE
148a1fd breaks mouse focus

### ISSUE THREAD

**Issue by cpiber** [dawsers/hyprscroller#74]
Since 148a1fd0f48789760b358e9786b953520ff1e128, whenever a popup (any floating window) closes, the focus is moved to the lower window, **moving my mouse to the center of that window**. It's extremely annoying, especially with xwayland windows like IntelliJ IDE's where each tooltip is a window.

**Comment by cpiber** [comment]
This simple thing fixes it, and it still solves #68:

```diff
--- a/src/scroller.cpp
+++ b/src/scroller.cpp
@@ -408,13 +408,7 @@ static void toggle_window_fullscreen_internal(PHLWINDOW window, eFullscreenMode
 }
 
 static void force_focus_to_window(PHLWINDOW window) {
-    g_pInputManager->unconstrainMouse();
     g_pCompositor->focusWindow(window);
-    g_pCompositor->warpCursorTo(window->middle());
-
-    g_pInputManager->m_pForcedFocus = window;
-    g_pInputManager->simulateMouseMovement();
-    g_pInputManager->m_pForcedFocus.reset();
 }
 
 static void switch_to_window(PHLWINDOW from, PHLWINDOW to)
```

I'm not sure why you originally had the mouse move stuff there? But it's *never* a good idea to move the user's mouse without their explicit action

**Comment by dawsers** [comment]
Thank you for the report. I am working on a fix. It will be committed soon.

The reason why I move the mouse is because I want the mouse in the window where I am typing. I use `follow_mouse =1`, so if don't warp the cursor, when I move the mouse, it will change focus to the window where it is at that time.

**Comment by dawsers** [comment]
Try cb5935603555b9a6601ab6383ee5855d8d88f87e. I think it should work the way you expect. If there are other side-issues you see, please let me know.

Thanks!

**Comment by cpiber** [comment]
Works perfectly, thank you!

**Comment by cpiber** [comment]
That said, I was trying around a bit, I think some calculations with moving the cursor are incorrect, maybe that's due to the animation still running? When I move left and right with the dispatcher, the mouse isn't exactly in the center, but rather offset in the direction I was moving, see this recording 

https://github.com/user-attachments/assets/c57d418e-83c7-4a26-82c7-4a456ec73cd4

**Comment by dawsers** [comment]
Yes. I use Hyprland's `CWindow::middle()`, and it uses the "real" size and position, so it's affected by the animation.

But I think it doesn't matter much. If you find an edge case where it matters, I can write my own function.

**Comment by cpiber** [comment]
Sorry to revive this yet again. Your fix is really nice, but I've noticed that it still bothers me. It turns out that when a window closes on another workspace, hyprscroller will steal the focus and move it to that workspace, even when I'm currently on another workspace (e.g. Virtualbox takes some time to shut down the VM, once it does I'm brought back, even switching workspace, not just monitor). You can trivially test it by opening two terminals on one workspace, running `sleep 3 && exit` in one and then switching workspace, it'll switch back

**Comment by dawsers** [comment]
Don't worry about it, I see the flaw. I will commit a fix soon. I was considering a closed window would always be active, but it doesn't have to be, like you said. Thanks.

**Comment by dawsers** [comment]
I think 11f5519a587b5838d6366d8b0dc9820e0bbc087d should do it.

**Comment by dawsers** [comment]
Thank you for filing these issues.
