### ISSUE TITLE
[Feature] Request/Idea: Window Rule for Window Size

### ISSUE THREAD

**Issue by BinaryInk** [dawsers/hyprscroller#76]
This occurred to me this morning after I was looking through the code last night trying to see if a "Remember Window Size" setting could be implemented to preserve the current window size when swapping would be feasible. While *that* doesn't seem possible based on the Hyprland interface--due to what appears to be a lack of functionality around window workspace changes (correct me if I'm wrong!)--but the *following* may be, I've yet to seriously look into the possibility.

---

It may be useful to allow window rules to override what `StandardSize` certain classes/titles of windows spawn with. e.g.:

```
windowrulev2 = plugin:scroller:columndefaultwidth one, class:(firefox)
windowrulev2 = plugin:scroller:rowdefaultwidth one, class:(firefox)

# or

windowrulev2 = plugin:scroller:columndefaultwidth onethird, class:(discord)
windowrulev2 = plugin:scroller:rowdefaultwidth onehalf, class:(discord)
```

---

It may be the case that a separate function is needed to accomplish this (`set_window_size(windowId, standardSize)`) which itself may be useful as a dispatcher?

Thoughts?

**Comment by dawsers** [comment]
When moving a window to a different workspace, Hyprland removes the window from the layout, "moves the window", and then adds it again. So all the state of the old window is lost, for the plugin it feels the same as when it creates a new one. So there is no simple "remember size" trick.

However, adding a window rule to set pre-determined widths and heights for new windows is possible. I could add that.

**Comment by dawsers** [comment]
Window rules are in 20eb2d8ca39d8c0f1405f17de4a6020f4bab1246

Relevant part of [README](https://github.com/dawsers/hyprscroller#window-rules)

I am going to close this as completed (title), so it doesn't merge with any possible issues with the new feature I am working on, which is more complicated.

**Comment by dawsers** [comment]
Now you can also move windows keeping their sizes and relative positions: see `selectiontoggle` and  `selectionmove`.

**Comment by BinaryInk** [comment]
Haven't even had the opportunity to incorporate the window rules yet! Thanks for the responsiveness and quick work, I'll be sure to check these out soon.
