### ISSUE TITLE
[Feature request] Toggle pin

### ISSUE THREAD

**Issue by nghialm269** [dawsers/hyprscroller#78]
Hi, thanks for making this plugin.
I'd like to ask if it's possible to pin/unpin a window using the same binding?

**Comment by dawsers** [comment]
It could be, but it wouldn't work the same way as it is now. Right now, you can `pin` a column that is not the currently *pinned* one. That will *unpin* the *pinned* one and *pin* the active column.  And by calling `unpin`, you *unpin* any *pinned* column, without having to go there.

If I made it a toggle, it would have to work this way:

When you call `pin`, if there is no *pinned* column, it will *pin* the active one. If there is a *pinned* one, if it is the current one, it will *unpin* it, but if it is a different one, it will *unpin* the *pinned* one, and *pin* the active one.

So to unpin a *pinned* column you would need to go to that column and call `pin`.

So you save a key binding, but have to work harder :-)

Let me know what you think.

**Comment by dawsers** [comment]
Another possibility for the toggle would be:

You need to call `pin` to *pin* a column. Then, no matter where you are, you need to call `pin` twice to *pin* a different one, once to *unpin* the currently *pinned* one, and the second to *pin* the active column. This is probably better.

**Comment by dawsers** [comment]
OK, I am convinced, committed in c63b7445f075b0237eb6aaffb7194c98903a4e95

Thanks!
