### ISSUE TITLE
does hyprscroller even work?

### ISSUE THREAD

**Issue by RambilE** [dawsers/hyprscroller#79]
I know that might sound stupid, but it.. doesn't work on my pc? I've checked multiple times different keybindings from tutorial, enabled the IPC script and it doesn't notify me of anything. I press the row keybinding or column keybinding, and nothing happens.
I've reinstalled hyprscroller multiple time and checked bindings, but nothing works.

When i thought that this was hyprpm's problem, i added hy3 plugin, and, upon loading, it instantly worked.

# The binds that i tried:
bind = $mainMod CTRL, home, scroller:movewindow, begin
bind = $mainMod CTRL, end, scroller:movewindow, end

bind = $mainMod, bracketleft, scroller:setmode, row
bind = $mainMod, bracketright, scroller:setmode, col

bind = $mainMod, equal, scroller:cyclesize, next
bind = $mainMod, minus, scroller:cyclesize, prev

bind = $mainMod, I, scroller:admitwindow,
bind = $mainMod, O, scroller:expelwindow,

Hyprpm says this:
→ Repository hyprscroller:
  │ Plugin hyprscroller
  └─ enabled: true

**Comment by dawsers** [comment]
It works for me.

Did you set it as your layout in your config?

```
general {
    layout = scroller
}
```

or activated it manually?:

```
hyprctl keyword general:layout scroller
```

**Comment by RambilE** [comment]
Oh, that's what i've did wrong. I didn't set the layout.
Sorry, i was kinda sleepy at that time and didn't pay too much attention
