### ISSUE TITLE
column_default_width, window_default_height, and cyclesize does not work

### ISSUE THREAD

**Issue by Linguiniotta** [dawsers/hyprscroller#82]
I have tried setting the `column_default_width` to maximized, floating, and other options, but all windows seems to open to the default `onehalf` width. The same issue happens with `window_default_height` which opens to the default `one` height. See GIF1.

```
general {
    layout = scroller
}

plugins {
    scroller {
        column_default_width = threequarters
        # floating # maximized
        window_default_height = threequarters
        # floating # maximized
        focus_wrap = true
        column_widths = twothirds onethird onefourth onesixth one
        window_heights = twothirds onethird onefourth onesixth one
    }
}

bind = $MainMod, equal, scroller:cyclesize, next
bind = $MainMod, minus, scroller:cyclesize, prev
```

![out](https://github.com/user-attachments/assets/6bb69ea8-bab7-4e33-996e-e8f8d833a113)

However, when launching with the `onworkspace:w[tv1]` window rule and `columnwidth` and `windowheight` to threequarters, it works as expected. Did the [Options](https://github.com/dawsers/hyprscroller?tab=readme-ov-file#options) get changed?

![hyprscroller2](https://github.com/user-attachments/assets/9b19dceb-83de-4ddf-8257-430ca50b9ba4)

---
The dispatchers `scroller:cyclesize` `next` and `prev` also seems to use the default value of `column_widths` (onehalf twothirds onethird) and `window_heights` (one onethird onehalf twothirds). As you can see in my configuration, I have set 5 column widths, but it only cycle 3 times (GIF 1).

---

Here is my `hyprctl version`
```
Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: Tue Nov 19 21:47:18 2024
Tag: v0.45.2, commits: 5451
built against aquamarine 0.5.0


flags set:
debug
```

**Comment by dawsers** [comment]
It's because you have a typo, it's `plugin`, not `plugins`.

This shoudl work:

```
plugin {
    scroller {
        column_default_width = threequarters
        # floating # maximized
        window_default_height = threequarters
        # floating # maximized
        focus_wrap = true
        column_widths = twothirds onethird onefourth onesixth one
        window_heights = twothirds onethird onefourth onesixth one
    }
}
```
