### ISSUE TITLE
Fullscreen results in windows on the workspace remaining "minimized" after exiting (kitty-related?)

### ISSUE THREAD

**Issue by BinaryInk** [dawsers/hyprscroller#83]
# Preamble

This is a pretty particular bug and is largely avoidable, so not urgent by any means. 

As far as I can tell, it's only happening when certain terminal applications are involved (I've tested KDE Konsole and Kitty) and it only affects certain applications thereafter. I can also confirm that this doesn't occur with Dwindle or Master layouts (in fact, switching to either layout shows the windows again--switching back to scroller thereafter and it doesn't fix the problem, the applications need to be closed and re-opened for them to work in scroller).

I suspect this has something to do with the mechanism that Konsole and Kitty use to go into fullscreen and could affect other programs that do something similar.

# Discovery, Description, & Nuances

I discovered the issue when I was using VSCode and Kitty together in fullscreen. It works as expected when in fullscreen with monacle-like behavior, but when I exit fullscreen, the kitty window is no longer "there" even though it can be focused.

- If I add in a Firefox window to the workspace, I will then be able to see the applications out of Fullscreen, but they're slits at the top of the screen and unusable. 
- If I have the Kitty terminal open, but don't focus on it while in fullscreen, the problem doesn't occur.
- If the Kitty terminal is the only application open in the workspace, the problem doesn't occur.
- If I open a Kitty terminal and Firefox...
  - If I fullscreen on the terminal and don't shift focus before exiting fullscreen, no problems occur.
  - If I fullscreen on the firefox and don't shift focus before exiting fullscreen, no problems occur.
  - *However*, if I fullscreen on either application and shift focus, the Firefox screen will go into "slit mode" and the Kitty terminal is unaffected after exiting fullscreen.

Errata:

- While Firefox is affected, I have not had an instance were VSCode and KDE Dolphin are affected.
- When focusing on the "hidden" window, if `input.follow_mouse=1` the cursor will move to the top left of the screen.

# Reproduction Steps

I think the above gives a lot of detail on how to trigger the problem in various ways with a small subset of applications, but just to provide a straightforward way to do so...

1. Open VSCode and open Kitty (or Konsole) in the same workspace.
2. Enter fullscreen using the Hyprland fullscreen dispatcher (not sure this is super relevant, but also occurs if using the application's fullscreen mechanism)
3. Focus on the terminal application.
4. Exit fullscreen.
5. You will be able to "focus" on the space where the terminal application *should* be, and can even interact with it with binds (e.g., quit the application, change it's size, etc).

# Screenshots

![image](https://github.com/user-attachments/assets/d2d5417d-f22c-4a62-8819-9f112223a7d3)
![image](https://github.com/user-attachments/assets/84fc125f-7b01-4139-8a88-f95276f70805)

**Comment by dawsers** [comment]
Are you running the latest version? I made some fixes to fullscreen mode yesterday.

**Comment by dawsers** [comment]
I see it now. I must have broken something. Let me have a look at it...

**Comment by dawsers** [comment]
I think this is fixed in db2ba190a9c9bfe636198b46724c5fc4e37dd986

**Comment by BinaryInk** [comment]
I can confirm this is fixed, thanks once more for your quick fixes to this plugin

**Comment by dawsers** [comment]
Thank you as always for taking the time to file these issues in such detail. I need to get better at QA. I am writing a document with tests before a major commit to reduce the number of regressions. But as the number of features increases, so do the possible interactions among them.
