### ISSUE TITLE
[Feature Request] Custom jump keys

### ISSUE THREAD

**Issue by skissue** [dawsers/hyprscroller#85]
Hi :wave: 

Thanks for introducing the "jump" functionality, it's quite impressive :sunglasses:. I was wondering if it'd be possible to have an  option to set a custom list of keys to use instead of the numbers? I've used similar "jump" functionality in other programs, and I like to use my homerow keys since it minimizes finger movement.

Thanks!

**Comment by dawsers** [comment]
Thank you.

It is definitely possible to add, but not totally trivial. I am currently working on a couple of bugs, but I will have a look at it once I am done.

**Comment by dawsers** [comment]
Added in 7d9fc423636635e8339e6c302fc84192959af345

The option is a string: `plugin:scroller:jump_labels_keys`, with a default of `1234`.
