### ISSUE TITLE
Disable `cyclewidth`, `cycleheight` wrap

### ISSUE THREAD

**Issue by Acumane** [dawsers/hyprscroller#95]
I do love moving between fixed proportions of the screen over the tedium of `resizeactive`. As reasoned in #9,
`plugin:scroller:cyclewidth_wrap = no`
`plugin:scrolleri:cycleheight_wrap = no`
—would be appreciated greatly

**Comment by dawsers** [comment]
This is something that I can add, no problem. However, the name `cycle` already implies sizing is cyclical :-)

**Comment by mattkang** [comment]
Love this @Acumane and agree @dawsers. Perhaps just "next" and "prev" or "increase" and "decrease" if ordered?

**Comment by dawsers** [comment]
This is implemented in f09abfe73bee1143533a34983227bf8967d6d160

The new option is `cyclesize_wrap` and affects both columns and windows.

**Comment by Acumane** [comment]
Two issues:
1. There are cases where the focused window is centered as if `center_row_if_space_available` was enabled. I can be more specific if you're unable to repro.
2. The `cycleheight` bounds are off by one (`[0 1 2]` is actually `0 1 ][ 2`), so the smallest size is actually the largest.

**Comment by dawsers** [comment]
1. I haven't been able to reproduce this. If you can, give me some steps to reproduce it, please.
2. I think you are probably using the default `column_widths` when enabling `cyclesize_wrap`. I may need to write a clearer explanation of how this works in the [README-cyclesize_wrap](https://github.com/dawsers/hyprscroller#cyclesize_wrap).

Basically, there is no ordering for sizes. you set them in whichever order you want in `column_widths` and `window_heights`, and then *hyprscroller* cycles through them, The default one is `onehalf twothirds onethird`, which would create a similar pattern to what you are seeing. Change the order to `onethird onehalf twothirds` if you want cycling to be by size. The README hints at that, but maybe it is not clear enough.

**Comment by Acumane** [comment]
Here's what's happening: if I have a `column_widths` list of `onethird onehalf twothirds one`, and I dispatch `scroller:setwidth 3`, our position in the list is updated. But if we resize by mouse, use `resizeactive` or `fitsize`, it is not. Since these methods don't transform windows to a preset length/width, we should find which size we're closest to in the list and set that as our index.
imo, this will make `scroller:cyclewidth`'s behavior less jarring

**Comment by dawsers** [comment]
Implemented in f477e656dd37c3fba77ca1d88e27575f26a9c2fa

Option is `cyclesize_closest`, `true` by default.

**Comment by Acumane** [comment]
I love you
