### ISSUE TITLE
Add border color for marked windows

### ISSUE THREAD

**Issue by Zhaith-Izaliel** [dawsers/hyprscroller#97]
I like to have the possibilty to see which windows are marked. Indeed, I can sometimes lose track of which were marked or not. It could be interesting to have an option to change the border color of any marked window, regardless of the mark. The default could fall back to the border color, when active or not.

Do you think it would be possible and feasible for hyprscroller ?

**Comment by dawsers** [comment]
Decorations are not simple, and when there are several, there may be conflicts (overwriting etc.). I could more easily add another IPC event, like there is for `trailmarks`, so you can set something on your bar to tell you if the active window is marked, maybe even the mark name. I know it is not the same, as you would have to be focused on that window to know if it's marked, but it would still give you the information, so you don't mark it again.

**Comment by Zhaith-Izaliel** [comment]
That could be a potential solution and would add more information you can gather for the IPC. I could be a decent tradeoff
